min_sensor_dist: .2
self_see_default_padding: 0.0
self_see_default_scale: 1.0
self_see_links:
  - name: l_gripper_palm_link
  - name: l_gripper_l_finger_link
  - name: l_gripper_r_finger_link
  - name: l_forearm_link